### ISSUE TITLE
Error parsing VCF file

### ISSUE THREAD

**Issue by apuhegde** [ekawaler/pyQUILTS#1]
Hi,
I get several lines of the following error when Quilts is reading my VCF file:

```
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
Error parsing:
.
.
.
.
./scripts/quilts_AH01.1.py:406: UserWarning: Failed to parse #CHROM     POS     ID      REF     ALT     QUAL
 warnings.warn("Failed to parse %s" % line)
```

This is my command:
`-bash-4.2$ python ./scripts/quilts_AH01.1.py --output_dir ./results --genome ./data/genome_hg19 --proteome ./data/refseq_hg19_20170922 --germline ./data/germline --somatic ./data/somatic --junction ./data/tophat --threshA 1 --threshAN 1 --threshN 1`

I haven't been able to figure out if it's because of the somatic or germline VCFs, or both. I believe the VCFs are in standardized format.
Please do let me know if you need any more information.

**Comment by ekawaler** [comment]
You get 654 "Error parsing" lines, correct? As per my email from a few weeks ago, those are the header lines of the vcf files - when it tries to write the line to log, the pound sign at the front of the line makes the shell think it’s commented out, so all we get is a blank line in the log. In the next version these will be gone, but there's no actual problem - the program just skips over them and moves on to the next lines.
