### ISSUE TITLE
What is required for a "reference proteome"?

### ISSUE THREAD

**Issue by verheytb** [ekawaler/pyQUILTS#12]
I have been trying to use pyQUILTS for the last little bit, but I’m looking for some guidance in setting up a reference. Specifically, I would like to use GRCh38, which is unsupported in the QUILTS web server.

Could you help me understand what files pyQUILTS is looking for? The usage says:

        --genome (path to a folder containing the reference genome)
        --proteome (path to a folder containing the reference proteome)

But is the genome a single FASTA file? What about the proteome? From scanning through the code, it looks like the “proteome” is a BED file, a FASTA file, a proteome-descriptions.txt file, and maybe more. Could you provide examples of what these are, and where you get them?

**Comment by ekawaler** [comment]
Try looking in the prepare_genome and prepare_proteome folders; instructions for setting up the reference genome and proteome are in there.

**Comment by verheytb** [comment]
Oh, completely missed it. Thanks!
