### ISSUE TITLE
New version of the code is not working

### ISSUE THREAD

**Issue by gwajnberg** [ekawaler/pyQUILTS#17]
When I run with the same parameters, the old code works... but with the new one thats what happen

/bin/sh: 1: /home/iarc/bin/pyQUILTS/read_chr_bed: Exec format error
ERROR: read_chr_bed didn't work - now we don't have a proteome.bed.dna file.
Aborting program.

python2.7 ~/bin/pyQUILTS/quilts.py  --output_dir quilts5/ --genome /References_data/References_genome/storage_back/ensemblGRCh37/ --proteome /References_data/References_genome/storage_back/proteome_refseq/  --somatic somatic/ --germline germline/ --junction junction/ --junction_file_type star --no_missed_cleavage

**Comment by ekawaler** [comment]
try recompiling read_chr_bed.c

**Comment by gwajnberg** [comment]
yep worked like magic! thanks
