### ISSUE TITLE
https://nyumc.box.com/v/quilts-sample-references not work

### ISSUE THREAD

**Issue by XinpeiYi** [ekawaler/pyQUILTS#18]
Hi, the link https://nyumc.box.com/v/quilts-sample-references in your readme txt file is not working now.

Would you like to upload a new one? Thanks

**Comment by HagemeijerRug** [comment]
Hi,
I just ran into the same issue. I will try to make my own reference in the meantime.
Thanks in advance.

**Comment by ekawaler** [comment]
Sorry, my university ended our support for Box so I had to move the samples. The link in the README has been updated. Thanks for pointing this out!
