### ISSUE TITLE
Trailing special characters in reference transcriptome file leading to errors

### ISSUE THREAD

**Issue by apuhegde** [ekawaler/pyQUILTS#2]
Hi,
In the reference transcriptome file (transcriptome.bed), the last two columns that are parsed in as "block_sizes" and "block_starts" in the function _filter_known_transcripts()_ contain trailing special characters and a comma, which cause the last value in the list when split by commas to be an empty string. This causes the following error to occur when the _int()_ function is applied to them:

```  File "/scratch/ahegde/pyQuilts/scripts/quilts_AH.py", line 1883, in <module>
    filter_known_transcripts(args.proteome+'/transcriptome.bed', results_folder+'/log', logfile)
  File "/scratch/ahegde/pyQuilts/scripts/quilts_AH.py", line 1209, in filter_known_transcripts
    sizes = map(int, block_sizes.split(','))
ValueError: invalid literal for int() with base 10: ''
```

I've debugged this by adding extra _strip()_ functions and the code is attached:
[TrailingSplCharacters_debugCode.py.txt](https://github.com/ekawaler/pyQUILTS/files/1674773/TrailingSplCharacters_debugCode.py.txt)

Could you please take a look and double check if this might introduce unintended errors in some other functions down the code?
Thanks!

**Comment by apuhegde** [comment]
FYI I noticed that the .bed files downloaded from UCSC genome browser in general seem to contain the trailing commas.

**Comment by ekawaler** [comment]
Resolved
