### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by xpgege** [ekawaler/pyQUILTS#20]
![image](https://user-images.githubusercontent.com/49704025/92927308-ef5fe900-f42c-11ea-89e6-486d37276ec2.png)
I just upload the junction file .
I got this error,so I wonder if the somatic or germline vcf file is necessary.

**Comment by ekawaler** [comment]
There was a bug where ref_prot wasn't generated in quite the right place so it failed if no germline/somatic variants were specified. That bug should be fixed now - try again with the new version?

**Comment by xpgege** [comment]
> There was a bug where ref_prot wasn't generated in quite the right place so it failed if no germline/somatic variants were specified. That bug should be fixed now - try again with the new version?

Thank you for your reply!
I correctly get the result. However, in the  output_dir/result/variant__proteome.fasta,I can only find the novel junction.
However can I get the type=bothConserved and type=donorConserved junction.

**Comment by xpgege** [comment]
> There was a bug where ref_prot wasn't generated in quite the right place so it failed if no germline/somatic variants were specified. That bug should be fixed now - try again with the new version?

Thank you for your reply!
I successfully get the result.
