### ISSUE TITLE
Source not found for shutil.copy() function

### ISSUE THREAD

**Issue by apuhegde** [ekawaler/pyQUILTS#3]
Hello,

The source path for the merged-junctions.filter.bed file seems to be hard-coded into the script and it's giving the following error:

```
File "./scripts/quilts_AH01.1.py", line 1906, in <module>
    shutil.copy('/ifs/data/proteomics/tcga/scripts/quilts/pyquilts/merged-junctions.filter.bed', results_folder+"/log/")
  File "/usr/lib64/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/ifs/data/proteomics/tcga/scripts/quilts/pyquilts/merged-junctions.filter.bed'
```

There seems to be such a file generated as part of the results in the ./results/log directory. Do I need to change the copy source path to this ./results/log directory or is this a different file/is there a working path you could provide that I can replace with in the script?
Thanks!

**Comment by ekawaler** [comment]
That line (1906) should be commented out. The function that generates that file takes a while to run so I commented it out and just copied over the file while I was testing later parts of the code.
