### ISSUE TITLE
ERROR with 'pyQUILTS/prepare_proteome/prepare_ensembl/prepare_ensembl.py'

### ISSUE THREAD

**Issue by hmkim** [ekawaler/pyQUILTS#8]
Hi, Thank you for your nice program (pyQUILTS)

When I try to setting the pyQUILTS,  I got the error in below.

![2018-08-28 15 25 29](https://user-images.githubusercontent.com/4966343/44704540-9be50180-aad6-11e8-9044-38d3570f9acb.png)

so, I checked the code.

If the line have no coordination of Genomic coding (Genomic coding start, Genomic coding end), this code is not work. 

<img width="913" alt="2018-08-28 15 18 02" src="https://user-images.githubusercontent.com/4966343/44704487-6e985380-aad6-11e8-8294-a96cfba01a8f.png">

so, I removed the rstrip function in code.

![2018-08-28 15 28 31](https://user-images.githubusercontent.com/4966343/44704643-1281ff00-aad7-11e8-970e-3dfd13c6507c.png)

Please check this issue.

**Comment by ekawaler** [comment]
I think it's been fixed now - instead of commenting out the line like you did, I strip off the carriage return, which was the original intention of the rstrip. Let me know if it works!

**Comment by hmkim** [comment]
Thank you!
